baseURL = 'https://esplaboratory.gitlab.io/esplab/'
languageCode = 'fr-fr'
title = 'ESPLaboratory'
theme = "beautifulhugo"


[Params]
  subtitle = "Electronic Security Programing Laboratory"

[Author]
  # Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
  name = "EspLab"
  #website = "https://chadi-mangle.github.io/Portfolio/"
  email = "esplaboratory@protonmail.com"
  github = "ESPLaboratory"
